# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 054486209d0fe1c7be910ef0d794b9af63de21af4d4b3967f399604caca625f04f493d0f2fb35822e222dd4e071f53892e159a9937918bb24f539c5b5d65c05f

test:
  secret_key_base: 282722b0cd50f54b245751a1149c0f2adbf1bd2d7c19599b0ae8284e9d0241b0658b29b317b8ad594031f299737a0d5ff65a960b3a48f18c0166f9e6f44af4ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
